name: Deploy to Azure Storage

on:
  push:
    branches:
      - master  # Adjust branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Upload files to Azure Storage
      run: |
        ls .
