name: Deploy to Azure Storage

on:
  push:
    branches:
      - master  # Adjust branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: {"clientSecret": "FkH8Q~tnKcV6oPx-09q3JLJ7YCqyPqfNpq3J1bwz",
                  "subscriptionId": "821c1871-a810-455b-8935-d3a2522aaf4a",
                "tenantId": "5bc08d06-98fa-4c98-87dd-ef8182447ce0",
                "clientId": "ec990bd7-d302-430b-b534-3d65638ea47f"
                }
    
    - name: Upload files to Azure Storage
      run: |
        az storage blob upload-batch --account-name bhavyanshu --account-key yKiHkv2dKwm2v68aTKxvK33CXhYRpuKRzFdFSSk6IbgqrhsuhgnGE5OeNNyGDVte/CMJmYHwvEjf+AStiVRetQ== --destination $web --source . --pattern "*.*"
